name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Repo'yu indir
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node.js kur
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. Bağımlılıkları yükle
      - name: Install dependencies
        run: npm install

      # 4. Cypress binary doğrula
      - name: Verify Cypress
        run: npx cypress install

      # 5. Cypress testlerini çalıştır
      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/dersÖrnekleri/API TESTS/apiTest.cy.js"


